name: Build and Deploy Frontend & Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: 'Checkout code'
        uses: actions/checkout@v3

      # Login to Azure
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      #########################
      # FRONTEND BUILD & DEPLOY
      #########################
      - name: 'Install frontend dependencies'
        working-directory: ./frontend
        run: npm ci

      - name: 'Build frontend'
        working-directory: ./frontend
        run: npm run build

      - name: 'Upload frontend to Azure Storage'
        run: |
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --destination '$web' \
            --source ./frontend/dist

      #########################
      # BACKEND BUILD & DEPLOY
      #########################
      - name: 'Install backend dependencies'
        working-directory: ./backend
        run: npm ci

      - name: 'Deploy backend to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: '<your-backend-webapp-name>'
          package: './backend'


