name: Deploy to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload to Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --connection-string ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} \
              --destination '$web' \
              --source '.'
